services:
    Sidus\DoctrineSerializerBundle\Serializer\EntityDenormalizer:
        arguments:
            - '@serializer.normalizer.object'
            - '@doctrine'
        tags:
            - { name: serializer.normalizer, priority: 2 }
